<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove="Helpers\ProxyEntityMapper.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Acornima" Version="1.6.2" />
        <PackageReference Include="BCrypt.Net-Core" Version="1.6.0" />
        <PackageReference Include="DeviceId" Version="6.11.0" />
        <PackageReference Include="IronPython" Version="2.7.11" />
        <PackageReference Include="JWT" Version="11.0.0" />
        <PackageReference Include="MaxMind.GeoIP2" Version="4.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.5" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
        <PackageReference Include="MimeKit" Version="4.16.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="SixLabors.ImageSharp" Version="2.1.11" />
        <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" VersionOverride="4.5.0" />
        <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RuriLib\RuriLib.csproj" />
    </ItemGroup>
</Project>